### ISSUE TITLE
PNG icons should be replaced with proper SVGs

### ISSUE THREAD

**Issue by Maran23** [Maran23/script-ide#11]
In order to solve https://github.com/Maran23/script-ide/issues/2 and make the icons look good in HiDPI mode, we should replace all icon PNGs with proper SVGs.

**Comment by gingerr** [comment]
First attempt at svg icons. Ive used Godot icons and recompositioned / recolered them. The zip includes the optimised svg files and Inkscape source files.

[script-ide-svg-icons.zip](https://github.com/Maran23/script-ide/files/12796256/script-ide-svg-icons.zip)

reference
https://docs.godotengine.org/en/latest/contributing/development/editor/creating_icons.html
https://github.com/godotengine/godot/tree/master/editor/icons
