### ISSUE TITLE
Allow Outline to optionally be on the left

### ISSUE THREAD

**Issue by Mickeon** [Maran23/script-ide#12]
I am experimenting with this addon, and so far I enjoy a lot of things about it. It's great potential that could someday even be in the core editor.

But there's one thing that I cannot get used to. The so-called Outline is to the right. The existing, built-in Script/Method list is on the left and it's what me, and possibly other users, have gotten accustomed to. Is it feasible to optionally move the new Outline to the left, instead?

**Comment by Maran23** [comment]
Sure. I will add a boolean constant in the code.
Later on I will experiment if those settings can be exposed via the project settings.

I agree, it would be nice to have this in core at one point. All major IDEs have an advanced Outline and a feature to quickly search for variables/methods. For now, I will experiment a bit with the plugin and at one point may write a proposal. :)
