### ISSUE TITLE
type icons too small on 4k display

### ISSUE THREAD

**Issue by gingerr** [Maran23/script-ide#2]
When looking on your screenshots the type icons in the outline (the filter on top and the icons before the symbols) they have a good size. On my 4k display they are too small, maybe half the size?

![image](https://github.com/Maran23/script-ide/assets/13162840/4d5f1fdf-bb27-460c-aad9-f64d2da66932)

**Comment by gingerr** [comment]
Ok I got some additional information. There is some scaling going on in Godot for the editor and it seems like your buttons/icons are not honoring it yet.

This is the automatic scaling which was chosen by Godot for me:
![image](https://github.com/Maran23/script-ide/assets/13162840/8b0facb0-319a-41db-ae98-e0293a885023)

This is how it looks when I set it to 'Custom' and select a scale of '3':
![image](https://github.com/Maran23/script-ide/assets/13162840/70c22748-1fc9-42a6-b4c2-b8aa3acfcb1c)

**Comment by Maran23** [comment]
May guess is that I need to change the icons to property SVGs. Will have a look.
