### ISSUE TITLE
Outline not working on built-in scripts

### ISSUE THREAD

**Issue by sepTN** [Maran23/script-ide#24]
Not sure if this is intentional, but as for now the outline is not working if you are editing on a built-in scripts (The one that isn't a stand alone .gd file)

![image](https://github.com/Maran23/script-ide/assets/13846022/08693f3b-fee1-4d9c-8abf-a88d7a5824b7)

**Comment by Maran23** [comment]
Never tested it with built-in scripts. I will check it out.
