### ISSUE TITLE
Cannot call method 'has_focus' on a null value

### ISSUE THREAD

**Issue by Nrosa01** [Maran23/script-ide#39]
I added this addon for the first time in a recently created project, and after a project reload I got this

![image](https://github.com/Maran23/script-ide/assets/62796415/bf4a0d7b-d106-4b64-90a0-26a5f607e405)

I have no idea why, so I just changed the line 255 of plugins.gd `if (!filter_txt.has_focus()):` for `if (not filter_txt or !filter_txt.has_focus()):`
I do have two more plugins: project timer tracker by fifut and inputmapperpresetloader by light1c3.  But uninstalling those did not fix it.
Is this error normal? I can make a PR but I'm not sure if this is something that shouldn't happen.

And well, even after changing that line, I still get some errors when closing or opening a tab

![image](https://github.com/Maran23/script-ide/assets/62796415/e5ccc927-28e6-48c0-a898-3fb42e9ef094)

**Comment by Maran23** [comment]
are you using Godot 4.2.1 or Godot 4.3.dev?

**Comment by HueVirtualCreature** [comment]
I am also seeing this issue in Output, while using Godot 4.2.1

**Comment by AaronKannon** [comment]
I'm having this same issue
Godot 4.2.1
![image](https://github.com/Maran23/script-ide/assets/28866153/db017542-f000-4e65-bbb7-101c09784631)

**Comment by Maran23** [comment]
Hm, I wonder what is different for you. It works for me and some friends are using it as well, no problems at all.
I will probably add a nullcheck so we fail safe, but it would be interesting to know what the root cause is.

**Comment by Nrosa01** [comment]
> are you using Godot 4.2.1 or Godot 4.3.dev?

I'm using Godot 4.2.1

**Comment by eldyer** [comment]
Same problem here, with 4.3.dev3.

**Comment by Maran23** [comment]
Found the problem, will submit a new update to the AssetLib soon.

**Comment by Maran23** [comment]
The update is on the asset store! Please install the plugin again and tell me if the bug is fixed for you! :)

**Comment by HueVirtualCreature** [comment]
Bug is fixed for me! Output is reporting no issues!
Thank you so much for the fast response!

**Comment by eldyer** [comment]
Everything works here too, thanks a lot! :+1:

**Comment by Nrosa01** [comment]
I've been using it for a while today and everything is working fine! Thank you!

**Comment by Maran23** [comment]
Thank you guys for reporting back!
