### ISSUE TITLE
Plugin features not working

### ISSUE THREAD

**Issue by Nrosa01** [Maran23/script-ide#40]
For some reason, the outline is not working, it's on the left instead of right, there are no coloour, I have less settings than your screenshots... Apart from all the other errors I mentioned.

![image](https://github.com/Maran23/script-ide/assets/62796415/2925b59c-bae1-4c2b-90b9-1c280d293f43)

![image](https://github.com/Maran23/script-ide/assets/62796415/2039dfd6-fad5-444b-a3ca-65919e9f3074)

I tried reinstalling the plugin but it doesn't work. You can see in that screenshot that I have "Outline Position Right" as true, but in the previous one it appears on the left. Control + O and Windows + O commands aren't working either

**Comment by Maran23** [comment]
Probably the same issue / caused by https://github.com/Maran23/script-ide/issues/39
