### ISSUE TITLE
File explorer on the left

### ISSUE THREAD

**Issue by Amealky** [Maran23/script-ide#42]
It could be perfect to add a file explorer of the current project on the left

So while working in full screen WE Can easily Switch between scripts ( even non opened one )

Thats for me the only missing feature ( except a run button directly into the view )

**Comment by Maran23** [comment]
While that might be a good addition, this is probably out of scope for such a plugin as of now.
Note that you can enable the script list and you can search for scripts native in Godot with a shortcut, so that should make the navigation a bit easier at least.

**Comment by Amealky** [comment]
Oh okay I didnt know we could do that 

I think this cover 99% of the need 

Thanks a lot for your work ❤️

**Comment by Maran23** [comment]
As discussed, this is out of scope for now. I may extend this plugin in the future, there are some promising changes in 4.3 that will make some new things possible, but until then, I will close this. :)
