### ISSUE TITLE
Add button to toggle all types in the outline

### ISSUE THREAD

**Issue by Frozenfire92** [Maran23/script-ide#45]
It would be helpful to toggle all off/on in the script outline

![image](https://github.com/Maran23/script-ide/assets/5893112/c34d60ba-fcbe-46e5-8b3d-175a65bd153c)

**Comment by Maran23** [comment]
I don't see any usecase why you would toggle all properties off. Checking other IDEs, I don't see any that has this feature.
So this does not seem like a usecase that people will often need, and it is easy to 'workaround'.

**Comment by Frozenfire92** [comment]
Hi @Maran23 

Sorry if I wasn't clear in the use case, and maybe the initial suggestion isn't the best solution. 

I want to be able to only toggle one at a time. Currently I have to unclick everything and then re-click it when I am done looking at that one specific type. While doable, it takes a few more clicks than most would like.

The suggestion of a toggle all off/on would provide a two click approach (turn all off, then turn one on) to get to the desired state, and then one click to get back (toggle all on).

Maybe a better solution would be to provide a shortcut `ctrl+click` to "only enable this type" and "enable all" if only that type was enabled.

I enjoy this plugin and how simple it is and appreciate you sharing/open sourcing it! Happy to help work on a solution as well

**Comment by Maran23** [comment]
I see, thanks for the example. I'm not yet sure how do that in a way that is obvious for all users. AFAIK, no other IDE has this kind of functionality, but the needs in Godot are also quite different from other, regular programming languages. I will think about it, maybe someone has an idea UX wise.

**Comment by Async0x42** [comment]
Could a right click be used to only enable a single filter? Then a new button doesn't need to be made, left click to toggle an individual filter, right click to disable all others and enable only the one that was right clicked on.

**Comment by Changryy** [comment]
I believe right click is the standard for this. I cant really think of any IDEs that have it because I dont typically use filtering, but it can be seen in other software. In FL Studio for example you can mute individual tracks or you can solo a single track (which mutes all other tracks). Left clicking will disable/mute the track. Right clicking will mute all other tracks. Right clicking on the same track again will unmute all the tracks

**Comment by Maran23** [comment]
Alright, since more and more people like this idea and proposed a right click, I will implement this as you guys noted.

That is: `Right click -> Enable the selected filter button, disable all others`
If already enabled (and the other disabled), the right click has no effect.

**Comment by Maran23** [comment]
So I downloaded and checked out FL Studio and can verify the behaviour as mentioned by @Changryy. I think this makes sense, therefore I implemented it the very same way. :)
