### ISSUE TITLE
Open script/outline search window: Auto-select first result

### ISSUE THREAD

**Issue by GustJc** [Maran23/script-ide#54]
A small enhancement to the _quick-switch_ search popups window would be to auto-select the first result in the search after typing something.

It's a bit annoying having to press 'down' then 'enter' to select the script even if there is only one result there.

![image](https://github.com/user-attachments/assets/bfc5bb92-c069-4e6f-971e-b2bead602977)

----
_PS: Great addon... its really useful, and a must-have._

**Comment by Maran23** [comment]
Thank you. 
This is a good enhancement. Other IDEs also do that as well. :)
