### ISSUE TITLE
Outline doesn't show

### ISSUE THREAD

**Issue by zegenie** [Maran23/script-ide#59]
Just downloaded the latest version from assetlib (and tried with latest git) but the Outline doesn't show up. Toggling it does nothing.

![image](https://github.com/user-attachments/assets/f4802922-dfc6-4b92-8835-c3475ababb86)

**Comment by Maran23** [comment]
Did you found the problem? I tried with a fresh project and everything worked as expected.

**Comment by zegenie** [comment]
I tried with a fresh install of Godot and it shows up. Not sure what is wrong with my current install, so just gonna close this up. Let me know if you need any logs or anything that could help you figure it out.

**Comment by Maran23** [comment]
If there was no error, I don't know what state could possibly cause this behavior. Since nobody did report this so far, will keep it closed and have an open eye in case this happens again.

**Comment by zegenie** [comment]
Yeah it was very strange, as there was no error in the output and nothing in the Godot logs even with verbose logging enabled.

Thanks for the plugin, and let me know if you want to investigate later.
