### ISSUE TITLE
create sub-menu in filesystem seems buggy?

### ISSUE THREAD

**Issue by luckybuzz** [Maran23/script-ide#62]
In Godot 4.3 stable, when I right-click a folder in Script-IDE's (Default) view, clicking any of the "create" options give the wrong result:

- clicking Create Script tries to create a Resource
- clicking Create Folder, Create Resource or Create TextFile does nothing
- clicking Create Scene tries to create a TextFile

Please let me know if there's any other info I can provide to help troubleshoot.  Thanks!

**Comment by Maran23** [comment]
My plugin does not change anything FileSystem related, so this seems odd. Could you upload a Video of it? My guess is that this might be Godot bug instead.
