### ISSUE TITLE
Add wrap around for outline filter icons

### ISSUE THREAD

**Issue by someThrowAway1900** [Maran23/script-ide#63]
Would it be possible to include wrap around for the filter icons like this?

![Capture](https://github.com/user-attachments/assets/e0851ecb-f350-4e7e-b8af-1984c28921a2)

The reasoning is to reduce the outline width, which would then increase the script working area width.

**Comment by someThrowAway1900** [comment]
I added a line to make the svg smaller, which effectively does the same. Thanks for a great addon.
closing.

func create_editor_texture(image: Image) -> ImageTexture:
	image.adjust_bcs(1.0, 1.0, get_editor_icon_saturation())
	image.resize(8, 8) # added code. not part of addon

**Comment by Maran23** [comment]
Interesting idea, I may check it out. Good idea to adjust the icon size. That is why I wrote the icon code this way - you can easily adjust it. Good that it works for you. :)
